write simple long type page returns error, suspect this is because type is different
java.lang.AssertionError: expected [42] but found [42]
Expected :42
Actual   :42